### ISSUE TITLE
Hello I got error I put telegram api and ngrok on container. py I got error 

### ISSUE THREAD

**Issue by wolfyy59** [sankethj/z-cam#10]
![Screenshot_20220205-162207](https://user-images.githubusercontent.com/60975463/152647796-f9142c0a-8c80-4eca-8efe-25bc72ae7252.png)

**Comment by wolfyy59** [comment]
![Screenshot_20220205-162311](https://user-images.githubusercontent.com/60975463/152647833-3744b05b-39da-4507-92b1-cbaee0bd9a34.png)
I let these empty?

**Comment by sankethj** [comment]
This isn't because of tokens. If you are using this in Android then you should "turn on" Hotspot.

**Comment by sankethj** [comment]
> ![Screenshot_20220205-162207](https://user-images.githubusercontent.com/60975463/152647796-f9142c0a-8c80-4eca-8efe-25bc72ae7252.png)

This isn't because of tokens. If you are using this in Android then you should "turn on" Hotspot.
