### ISSUE TITLE
Page couldn't load 

### ISSUE THREAD

**Issue by wolfyy59** [sankethj/z-cam#11]
Everything is installed correctly except when I load link I got this errors what should I do? 
![Screenshot_20220215-135501](https://user-images.githubusercontent.com/60975463/154207589-b1391a03-9c21-461e-a860-11b2673806c4.png)

![Screenshot_20220216-072003](https://user-images.githubusercontent.com/60975463/154207919-6ddeab43-71f6-42bc-86ae-7c094d46784b.png)

**Comment by sankethj** [comment]
Elaborate your issue... Your Image isn't uploaded properly.

**Comment by sankethj** [comment]
Turn on "hotspot" if you are on Android.

**Comment by wolfyy59** [comment]
> Turn on "hotspot" if you are on Android.

I have a rooted phone while, however you when you tried it on termux u turned Hotspot?

**Comment by sankethj** [comment]
How will you tunnel without hotspot on Android?
