### ISSUE TITLE
missing directory capture

### ISSUE THREAD

**Issue by Samuel88** [sankethj/z-cam#13]
If directory **capture** is missing script fail with error
`FileNotFoundError: [Errno 2] No such file or directory: 'capture/img_2022-05-16 10:41:09.808373.png'`

**Comment by sankethj** [comment]
Unknowingly I have deleted that directory from repo. 
To solve just create an empty directory inside z-cam directory. 
```
cd z-cam
mkdir capture
```

Or pull the new repo I have added it now.
