### ISSUE TITLE
TELEBOT ERROR

### ISSUE THREAD

**Issue by Christopalace01** [sankethj/z-cam#17]
always getting this error anytime i run the program

raceback (most recent call last):
  File "/home/christopalace/z-cam/zcam.py", line 3, in <module>
    from telebot import types
ModuleNotFoundError: No module named 'telebot'

**Comment by sankethj** [comment]
Please wait for a day, I'll resolve all errors and update to you.

**Comment by Christopalace01** [comment]
thanks

**Comment by sankethj** [comment]
Follow the instructions given (go through readme.md again). You have not installed telebot library.
