### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by sami3898** [sankethj/z-cam#5]
After installing the requirements I have tried to run the script but it is throwing some exceptions.
Please update me on this.
Thank you.
![Screen Shot 2022-01-03 at 7 50 54 PM](https://user-images.githubusercontent.com/32996863/147941746-a5698d5d-e8be-40f0-9918-0409698793b2.png)

**Comment by sankethj** [comment]
You haven't installed ngrok library properly. 

`pip3 install pyngrok`

Then run the script, it should work properly.

**Comment by sami3898** [comment]
Okay thanks I'll give it a try

**Comment by sankethj** [comment]
Ngrok have made compulsory to include auth-token, so wait until tomorrow. I will release one major update on zcam including that.

**Comment by sankethj** [comment]
> Okay thanks I'll give it a try

Use newer version.....
