### ISSUE TITLE
how can i fix it?

### ISSUE THREAD

**Issue by datlmhg** [sankethj/z-cam#9]
![image](https://user-images.githubusercontent.com/86174857/150916562-06d0fbe9-413c-4b85-98e9-83c1d696b71a.png)

![image](https://user-images.githubusercontent.com/86174857/150916620-b7c5477f-4e5a-4089-8bf7-1ad433e8d63f.png)

**Comment by sankethj** [comment]
Create your own bot token and add it and try.

**Comment by sankethj** [comment]
> ![image](https://user-images.githubusercontent.com/86174857/150916562-06d0fbe9-413c-4b85-98e9-83c1d696b71a.png)
> 
> ![image](https://user-images.githubusercontent.com/86174857/150916620-b7c5477f-4e5a-4089-8bf7-1ad433e8d63f.png)

Use your own tokens, I have explained clearly in the video. Create your tokens and add it in the constraints.py file
